1. Django/1. 기초/render을 사용한 화면 구현/testapp/urls.py
# 프로젝트 urls에서 include한 경우에
# 앱 내 직접 파일 만들어서 추가해줘야한다!

from django.urls import path
from . import views
# 해당 앱 내의 views를 불러올거니까 .으로 표현

app_name = 'testapp'

urlpatterns = [
    path('first/', views.first, name='first'),
    path('second/', views.second, name='second'),
    # 앱 이름과 함수(경로)이름 지정해주기-html에서 urls로 이동시킬때 사용됨
    # 앱:경로명 이런 형식으로!
    path('third/<str:sam>/', views.third, name='third'),
    # 주소(url)에 변수(view함수 인자로 전달 가능)를 포함시키는 것
    # <타입:이름> 형태로 저장!
]

1. Django/1. 기초/render을 사용한 화면 구현/testpjt/urls.py
from django.contrib import admin
from django.urls import path, include
# include 쓸 때는 import 해주는 거 잊지말기!
from testapp import views
# 앱에서 views.py로 갈거니까 그거 불러오기 한다고 알려주기!

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index),
    # views.py의 어떤 함수를 쓰는 건지 알려주기!
    # 앱에는 
    path('testapp/', include('testapp.urls')),
    # 앱의 urls로 가도록 하는 거! 
    # 앱의 urls로 갔을 때는 앱의 모든 urls 주소들이 다 testapp/으로 시작한다
    # include 쓰면 앱이름.ulrs(가리키는 곳이 urls.py겠지?!)로 될 수 있도록
]

1. Django/1. 기초/render을 사용한 화면 구현/testapp/models.py
from django.db import models

# Create your models here.

# django.db.models 모듈에 Model이라는 부모 클래스 상속 이라는 뜻
# Model이라는 부모클래스에는 model에 관련된 모든 코드가 이미 작성되어 있음
# 이게 바로 프레임워크의 장점! 다 코드가 짜져있으니까 중요 테이블 구조를 어떻게 설계할지만 생각하면 된다.

class Article(models.Model):
    # 모델 클래스 만들고
    # 아래에 DB 테이블에 저장될 명칭과 제약조건, 입력 데이터 타입을 적어주기
    # 필드 명칭 = models.입력할 데이터 타입(제약조건) 형식
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    # 처음 생성될 때 기준으로만 시간 저장
    updated_at = models.DateTimeField(auto_now=True)

# 모델에 저장한 후 DB에 migration 해주는 거 잊지마!!
# bash에 
# python manage.py makemigrations
# python manage.py migrate
# 입력하기

# migration 되었는 지 확인하려면 
# python manage.py showmigrations 해서 확인하기
# X라고 되어있으면 migrate 완료된 것!

# 그 다음은 admin.py에 모델클래스 등록해서 admin사이트에서 볼 수 있도록 하기!

1. Django/1. 기초/render을 사용한 화면 구현/testapp/views.py
from django.shortcuts import render

# -------------------------------------------------------------------------------------

def index(request):
    # 무조건 request를 매개변수로 받아야한다.
    # 거기에 추가로 원하는 거(예) pk 등) 더 받아 올 수 있음
    return render(request, 'testapp/index.html')
    # 매개변수, 이동할 템플릿, 딕셔너리(이거는 선택사항)

# -------------------------------------------------------------------------------------

def first(request):
    return render(request, 'testapp/first.html')

# -------------------------------------------------------------------------------------

def second(request):
    # 다른 곳에서 받아오는 건 여기다 어떤 거 받아올 지 적어줘야해!!!!!!
    # request.GET 요청 중 딕셔너리 받아오는 거 의미하거든?
    # 그래서 get()함수를 써서 받아오는 곳의 어느 요소 이름(키의 값)을 가지고 올지 확인해야해!
    ID = request.GET.get('name')
    password = request.GET.get('bimil')
    # ★ GET을 통해 받으면 받는 곳으로 바로 넘어가게 되어있더라!! 신기해!!!
    content = {
        'ID' : ID,
        'password' : password,
        # 키는 문자열!!!!! 값은 위에 저장된 변수!!!!!!
    }
    return render(request, 'testapp/second.html', content)

# -------------------------------------------------------------------------------------

def third(request, sam):
    # url에서 받아온 변수를 인자로 받음
    name = sam
    content = {
        'name':name,
}
    return render(request, 'testapp/third.html', content)

# -------------------------------------------------------------------------------------

1. Django/1. 기초/render을 사용한 화면 구현/testapp/templates/testapp/first.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <form action="{% url "testapp:second" %}" method='GET'>
    <!--method 방법에는 GET과 POST가 있고, 
      GET은 단순 화면만 보여주는? 단순 정보만 보내는 느낌,
    POST는 그 정보들을 가지고 수정할 수 있도록, 처리할 수 있도록 하는 거
  POST를 쓸 때는 {% csrf_token %}이 필요하다!-->
  <!--action에는 이걸 어디에 쓸건지라 어디로 보낸다(전송된다)가 들어가면 된다..!-->
  <!--url 대신 아무것도 안쓰면 현재 페이지의 url로 보내지는 것!-->
  <!--url 태그 쓰면 특정 앱의 특정 경로 주소로 보내게 되는 것!-->
  <!--그냥 url태그 없이 주소만 적어도 상관 없음
    (/testapp/second/처럼 혹은 https://www.naver.com/뭐 이런거)-->
    <div>
    <label for="id">이곳은 input값의 이름을 달아주는 곳입니다. 
      <br> for이 어디 input id를 참조하는 지 알아보는 거에요.</label>
    <input type="text" id='id' name='name'>
    <!--글을 입력할 수 있는 input-->
    <!--여기에 name=''을 추가하면 외부에서 사용하는 값이 지정되는 거죠!-->
  </div>
  <div>
    <label for="password">비밀번호는 자동으로  비밀번호 입력하도록 떠요.</label>
    <input type="password" id='password' name='bimil'>
    <input type="submit" value='이게 보내는 것! input 통해서 보내기'>
    </div>
  </form>
</body>
</html>

1. Django/1. 기초/render을 사용한 화면 구현/testapp/templates/testapp/index.html
<!--템플릿은 폴더부터 새롭게 만들어줘야한다!!-->
<!--여기는 html들 모아놓는 곳!-->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <p>안녕하세요!!</p>
</body>
</html>

1. Django/1. 기초/render을 사용한 화면 구현/testapp/templates/testapp/second.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <p>ID는 {{ ID }}, 비밀번호는 {{ password }}</p>
</body>
</html>

1. Django/1. 기초/render을 사용한 화면 구현/testapp/templates/testapp/third.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <p>{{ name }}입니다!</p>
</body>
</html>